### ISSUE TITLE
Download issues with 9anime and kissanime

### ISSUE THREAD

**Issue by WhoPunkedU** [vn-ki/anime-downloader#17]
When I tried to download the Black Clover Dub from 9anime it came up with a failure notice.

`anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issueshere https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue`

It seems like nobody else has this problem, so I think my setup is wrong

**Comment by TheRhysWyrill** [comment]
You're not alone, i've also encountered this error, for me it happens no matter what anime and it happens on both 9Anime and KissAnime.

**Comment by WhoPunkedU** [comment]
Also, when I did all the stuff to start downloading off of kissanime, it came up with this issue with the same anime

`TypeError: get_stream_url_rapidvideo() missing 1 required positional argument: 'headers'`

**Comment by vn-ki** [comment]
> You're not alone, i've also encountered this error, for me it happens no matter what anime and it happens on both 9Anime and KissAnime.

For accessing kissanime, you have to install with cloudflare support. (It's mentioned in the readme)
```
pip install anime-downloader[cloudflare]
```

> Also, when I did all the stuff to start downloading off of kissanime, this issue came up with the same anime

That is a bug. I'll look into it ASAP.

**Comment by vn-ki** [comment]
@WhoPunkedU I have released anime-downloader 2.6.1 which should fix that issue.
Update with
```
pip install -U anime-downloader[cloudflare]
```

**Comment by WhoPunkedU** [comment]
The issue is still happening even after I ran that line. I'm thinking about just re-downloading everything

**Comment by vn-ki** [comment]
I have only fixed the kissanime issue. Try it with kissanime. Post your output if it's still not working.

**Comment by Enderlein** [comment]
> Post your output if it's still not working.

And your exact input, too.

**Comment by WhoPunkedU** [comment]
its working, thanks for the help

this was my input every time: `anime dl "black clover" --provider kissanime`

**Comment by vn-ki** [comment]
@WhoPunkedU If you want to make kissanime default, you can do that by changing the provider key value, in the config file. (Under `AppData` or something in windows and `~/.config/anime-downloader` in linux) 

@Enderlein Can you update the config wiki with Windows specific folder(I wasn't sure where the config file resided when I wrote the wiki). Link: https://github.com/vn-ki/anime-downloader/wiki/Config

**Comment by Enderlein** [comment]
@vn-ki Done

**Comment by WhoPunkedU** [comment]
set up the config, thanks for all the help guys
