### ISSUE TITLE
'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by danielb2** [vn-ki/anime-downloader#205]
**Describe the bug**
``` bash
[~]$ anime dl hero
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'
```

**To reproduce**

``` bash
anime dl hero
```

This was a fresh install because of:

<img width="452" alt="Screen Shot 2019-06-27 at 11 08 15" src="https://user-images.githubusercontent.com/26678/60290307-55fef280-98cd-11e9-84d6-3181974fefff.png">
🎉 🎉 🎉 

Here's the command history when I was trying it:

<img width="558" alt="Screen Shot 2019-06-27 at 11 12 20" src="https://user-images.githubusercontent.com/26678/60290342-6dd67680-98cd-11e9-9845-cc12ce49ff03.png">

<details>
<summary>LOG</summary>

```
[~]$ anime dl hero --log-level DEBUG
INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Darwin-18.2.0-x86_64-i386-64bit
DEBUG root: Python 3.7.3
DEBUG root: https://www4.9anime.to/search?keyword=hero
ERROR root: 'NoneType' object has no attribute 'find_all'
```

**Comment by danielb2** [comment]
Does the app store state somewhere ? I should be able to get it back to working like the first time

**Comment by akukreja96** [comment]
Yeah I am getting this same error message when running the command

`anime watch 'one punch man' -n`

Searching for other terms also gives me this same issue.

**Comment by vn-ki** [comment]
@danielb2 Can you try other providers?

**Comment by danielb2** [comment]
works with whatever provider I specified in the defaults now. Still getting this error for 9anime

**Comment by danielb2** [comment]
```
[~/tmp]$ anime dl 'made in abyss' --provider kisscartoon
/Users/daniel/Library/Application Support/anime downloader
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'
```

Also problems with kisscartoon.  and twist.moe just crashes

<details>
<summary>error output from twist.moe</summary>
[~/tmp]$ anime dl 'made in abyss' --provider twist.moe
/Users/daniel/Library/Application Support/anime downloader
anime: anime-downloader 3.6.3
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==3.6.3', 'console_scripts', 'anime')()
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/anime_downloader/cli.py", line 102, in dl
    anime_url = util.search(anime_url, provider)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/anime_downloader/util.py", line 59, in search
    cls = get_anime_class(provider)
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/anime_downloader/sites/init.py", line 21, in get_anime_class
    'anime_downloader.sites.{}'.format(site[0])
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/anime-downloader/3.6.3/libexec/lib/python3.7/site-packages/anime_downloader/sites/twistmoe.py", line 1, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'
</details>

**Comment by vn-ki** [comment]
Can you try installing with `--HEAD`?

**Comment by vn-ki** [comment]
Also, for twist, you need to do 

```
pip install pycryptodome
```

**Comment by danielb2** [comment]
> Also, for twist, you need to do `pip install pycryptodome`

Can we add that to the installation steps?  Also, I noticed that https://github.com/vn-ki/anime-downloader/wiki/Config  Doesn't contain the path to macos config file ( ~/Library/Application Support/anime downloader )

trying with --HEAD:

<details>
<summary>[~/L/A/anime downloader]$ pip install pycryptodome</summary>
<pre>
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pycryptodome
  Downloading https://files.pythonhosted.org/packages/72/5c/23d88d4abc189ea847c2ebf69dc4d610e1a2bd3a611f29fd3ac1fd1e2e71/pycryptodome-3.8.2-cp27-cp27m-macosx_10_6_intel.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 825kB/s
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.8.2
</pre>
</details>

<details>
<summary>anime dl 'made in abyss' --provider kisscartoon</summary>
<pre>
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycryptodome>=3.8.2' distribution was not found and is required by anime-downloader
</pre>
</details>

**Comment by vn-ki** [comment]
```
pip3 install pycryptodome
```

Sorry

**Comment by vn-ki** [comment]
Also, try twist

```
anime dl 'made in abyss' --provider twist.moe
```

**Comment by vn-ki** [comment]
> Can we add that to the installation steps?

It is not required anymore with the master branch.

If it still doesnt work, please remove everything and install again with `--HEAD`

**Comment by danielb2** [comment]
Still issues. attaching screenshot this time so you can make sure I'm doing it right.

<details>
<summary>screenshot</summary>
<img width="730" alt="Screen Shot 2019-07-12 at 10 54 20" src="https://user-images.githubusercontent.com/26678/61148364-71542b00-a493-11e9-9259-ca943e8cdc51.png">
</details>

**Comment by vn-ki** [comment]
This is something up with brew

DO

```
/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/lib/pip install -U pycryptodome
```

Then you can use everything else

**Comment by vn-ki** [comment]
@nandahkrishna can you update the brew formula with pycryptodome dependency?

**Comment by danielb2** [comment]
looks like my HEAD is different from yours, but this is what I did

<img width="740" alt="Screen Shot 2019-07-12 at 11 00 29" src="https://user-images.githubusercontent.com/26678/61148740-5209cd80-a494-11e9-8070-78f4307b377e.png">

**Comment by vn-ki** [comment]
```
/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/bin/pip install -U tabulate
```

The problem is that I've rewritten the application since it was released on brew and the new dependencies are not there yet

**Comment by vn-ki** [comment]
```
/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/bin/pip install -U requests-cache
/usr/local/Cellar/anime-downloader/HEAD-7d3e6aa/libexec/bin/pip install -U coloredlogs
```

is required too

**Comment by danielb2** [comment]
Ya, I got those, and:

```
[~/L/A/anime downloader]$ anime dl 'made in abyss' --provider twist.moe
ERROR: No module named 'anime_downloader.commands'
```

**Comment by vn-ki** [comment]
Okay, the best thing to do is to abandon brew until this is fixed

uninstall anime dl from brew and do

```
pip3 install -U git+https://github.com/vn-ki/anime-downloader.git
```

**Comment by danielb2** [comment]
Still no pass :(

<img width="763" alt="Screen Shot 2019-07-12 at 11 27 04" src="https://user-images.githubusercontent.com/26678/61150326-0b1dd700-a498-11e9-9194-6cd4c3c18e08.png">

**Comment by vn-ki** [comment]
Can you hop on discord? https://discord.gg/Qn2nWGm

**Comment by vn-ki** [comment]
Also, I've pushed an update. please try

```
pip3 install -U git+https://github.com/vn-ki/anime-downloader.git
```

again

**Comment by danielb2** [comment]
Just for record, the latest update fixed it.

**Comment by gingerbeardman** [comment]
Jus to clarify for any new people (like me!)... October 2019...

Installing on macOS using `brew` it is still broken.

`pip3 install -U git+https://github.com/vn-ki/anime-downloader.git` works.
